from __future__ import annotations

import bisect
import gzip
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


@dataclass(frozen=True)
class TapeFrame:
    sample_index: int
    world_frame: int
    sim_time: float
    delta_seconds: float
    control: Dict[str, Any]
    ego_location: Tuple[float, float, float]
    ego_rotation: Tuple[float, float, float]
    ego_speed: float
    raw: Dict[str, Any]


class BehaviorTape:
    """Read a probe run and provide timestamp-indexed replay controls.

    The loader intentionally supports both the earlier Probe Listener schema
    used by the project (``world.elapsed_seconds`` / ``ego.applied_control``)
    and the compact v2 schema generated by the restored listener.
    """

    def __init__(self, run_dir: str):
        self.run_dir = Path(run_dir).expanduser().resolve()
        self.frames_path = self._find_frames_file(self.run_dir)
        self.frames = self._load_frames(self.frames_path)
        if not self.frames:
            raise ValueError("behavior tape is empty: %s" % self.frames_path)

        self.times = [frame.sim_time for frame in self.frames]
        self.first_time = self.times[0]
        self.last_time = self.times[-1]
        self.dt = self._infer_dt(self.frames)
        self._validate_monotonic()

    @staticmethod
    def _find_frames_file(run_dir: Path) -> Path:
        candidates = [
            run_dir / "frames.jsonl.gz",
            run_dir / "frames.jsonl",
            run_dir / "behavior.jsonl.gz",
            run_dir / "behavior.jsonl",
        ]
        for path in candidates:
            if path.is_file():
                return path
        raise FileNotFoundError(
            "cannot find frames.jsonl[.gz] or behavior.jsonl[.gz] under %s"
            % run_dir
        )

    @staticmethod
    def _open_text(path: Path):
        if path.suffix == ".gz":
            return gzip.open(str(path), "rt", encoding="utf-8")
        return path.open("r", encoding="utf-8")

    @classmethod
    def _load_frames(cls, path: Path) -> List[TapeFrame]:
        result: List[TapeFrame] = []
        with cls._open_text(path) as handle:
            for index, line in enumerate(handle):
                line = line.strip()
                if not line:
                    continue
                raw = json.loads(line)
                result.append(cls._parse_frame(raw, len(result)))
        return result

    @staticmethod
    def _vec3(value: Any) -> Tuple[float, float, float]:
        if isinstance(value, dict):
            return (
                float(value.get("x", 0.0)),
                float(value.get("y", 0.0)),
                float(value.get("z", 0.0)),
            )
        if isinstance(value, (list, tuple)):
            values = list(value) + [0.0, 0.0, 0.0]
            return (float(values[0]), float(values[1]), float(values[2]))
        return (0.0, 0.0, 0.0)

    @staticmethod
    def _rotation(value: Any) -> Tuple[float, float, float]:
        # Canonical order used here is pitch, roll, yaw.
        if isinstance(value, dict):
            return (
                float(value.get("pitch", 0.0)),
                float(value.get("roll", 0.0)),
                float(value.get("yaw", 0.0)),
            )
        if isinstance(value, (list, tuple)):
            values = list(value) + [0.0, 0.0, 0.0]
            return (float(values[0]), float(values[1]), float(values[2]))
        return (0.0, 0.0, 0.0)

    @classmethod
    def _parse_frame(cls, raw: Dict[str, Any], default_index: int) -> TapeFrame:
        world = raw.get("world") or {}
        ego = raw.get("ego") or {}

        # Old Probe Listener schema.
        if "state" in ego or "applied_control" in ego:
            state = ego.get("state") or {}
            transform = state.get("transform") or {}
            location = cls._vec3(transform.get("location"))
            rotation = cls._rotation(transform.get("rotation"))
            velocity = cls._vec3(state.get("velocity"))
            speed = math.sqrt(sum(item * item for item in velocity))
            control = ego.get("applied_control") or {}
            return TapeFrame(
                sample_index=int(raw.get("sample_index", default_index)),
                world_frame=int(world.get("frame", raw.get("world_frame", -1))),
                sim_time=float(world.get("elapsed_seconds", raw.get("sim_time", 0.0))),
                delta_seconds=float(world.get("delta_seconds", raw.get("delta_seconds", 0.0))),
                control=dict(control),
                ego_location=location,
                ego_rotation=rotation,
                ego_speed=float(ego.get("speed", speed)),
                raw=raw,
            )

        # Compact restored schema.
        transform = ego.get("transform") or {}
        location = cls._vec3(transform.get("location", ego.get("location")))
        rotation = cls._rotation(transform.get("rotation", ego.get("rotation")))
        velocity = cls._vec3(ego.get("velocity"))
        speed = float(ego.get("speed", math.sqrt(sum(item * item for item in velocity))))
        control = raw.get("control") or ego.get("control") or {}
        return TapeFrame(
            sample_index=int(raw.get("sample_index", default_index)),
            world_frame=int(raw.get("world_frame", world.get("frame", -1))),
            sim_time=float(raw.get("sim_time", world.get("elapsed_seconds", 0.0))),
            delta_seconds=float(raw.get("delta_seconds", world.get("delta_seconds", 0.0))),
            control=dict(control),
            ego_location=location,
            ego_rotation=rotation,
            ego_speed=speed,
            raw=raw,
        )

    @staticmethod
    def _infer_dt(frames: List[TapeFrame]) -> float:
        diffs = [
            frames[i + 1].sim_time - frames[i].sim_time
            for i in range(len(frames) - 1)
            if frames[i + 1].sim_time > frames[i].sim_time
        ]
        if not diffs:
            return float(frames[0].delta_seconds or 0.1)
        diffs.sort()
        return float(diffs[len(diffs) // 2])

    def _validate_monotonic(self) -> None:
        for previous, current in zip(self.frames[:-1], self.frames[1:]):
            if current.sim_time <= previous.sim_time:
                raise ValueError(
                    "behavior tape time is not strictly increasing: %.6f -> %.6f"
                    % (previous.sim_time, current.sim_time)
                )

    def nearest(self, sim_time: float) -> TapeFrame:
        if sim_time <= self.first_time:
            return self.frames[0]
        if sim_time >= self.last_time:
            return self.frames[-1]
        idx = bisect.bisect_left(self.times, sim_time)
        before = self.frames[idx - 1]
        after = self.frames[idx]
        if abs(before.sim_time - sim_time) <= abs(after.sim_time - sim_time):
            return before
        return after

    def frame_for_replay_time(
        self,
        run_timestamp: float,
        time_offset_seconds: float = 0.0,
    ) -> Optional[TapeFrame]:
        """Map Leaderboard run_step(timestamp) to the recorded simulation time.

        This is the timestamp-indexed rule that removed the previously observed
        fixed 2.1 s / 21-tick replay delay. Before the first recorded timestamp
        the caller should return neutral control rather than dropping tape rows.
        """
        target = float(run_timestamp) + float(time_offset_seconds)
        tolerance = max(1e-4, self.dt * 0.51)
        if target < self.first_time - tolerance:
            return None
        if target > self.last_time + tolerance:
            return self.frames[-1]
        frame = self.nearest(target)
        if abs(frame.sim_time - target) > tolerance:
            raise RuntimeError(
                "no tape sample near replay time %.6f (nearest %.6f, dt %.6f)"
                % (target, frame.sim_time, self.dt)
            )
        return frame

    def by_index(self, index: int) -> TapeFrame:
        if index < 0 or index >= len(self.frames):
            raise IndexError(index)
        return self.frames[index]

    def index_at_relative_time(self, relative_time_s: float) -> int:
        target = self.first_time + float(relative_time_s)
        frame = self.nearest(target)
        return self.frames.index(frame)

    def sim_time_for_index(self, index: int) -> float:
        return self.by_index(index).sim_time

    def relative_time_for_index(self, index: int) -> float:
        return self.sim_time_for_index(index) - self.first_time
